### ISSUE TITLE
panprog - PythOracle allows any user to commit non-requested oracle version for any timestamp after the previous commit even if it's long ago which can be abused to steal from the protocol via price manipulation and collateral removal

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-perennial-judging#43]
panprog

high

# PythOracle allows any user to commit non-requested oracle version for any timestamp after the previous commit even if it's long ago which can be abused to steal from the protocol via price manipulation and collateral removal
## Summary

PythOracle allows any user to commit non-requested oracle version. The only restriction is for the commit timestamp specified by the user to be after the previous commit. If there were no commits nor oracle requests for some time, it is possible to manipulate the price to steal funds from protocol. Since collateral change is the only operation which can be done without first requesting a price, we can use it to "close" positions via removing max collateral at artificial price and abandoning it with a bad debt (additionally profiting from liquidating it).

## Vulnerability Detail

The theft scenario (consider leverage = 100 is allowed):
1. Use 2 accounts to open 1 ETH long and 1 ETH short positions at $1000, each with $100 collateral
2. Monitor pyth prices and record all prices with signatures every second, wait for the following conditions:
- current price is greater than $1020
- AND interval min price is less than $980 (this can also be reversed)
3. As soon as the conditions are met, commit oracle version at the timestamp of min price with that price (say, $980)
4. Remove $110 of collateral from short position (which has $20 profit from the latest oracle commit), leaving it with $10 collateral (at the $980 price user has commited). It passes, because user is now at leverage = 98, which is allowed.
5. Initiate closing long position and initiate liquidating short position (this creates oracle request)
Steps 3-5 can be done in a single transaction
6. Fulfill oracle request with a price = $1020.
7. Settle market: receive $20 profit from long position and remove $120 collateral from it, receive some liquidation fee from the short position, even though it's in a bad debt.

Result: from initial $200 deposit get back $230 + liquidation fee

There are a few conditions to be able to steal, but all of them are feasible, although not in all markets:
1. Market has a stale price check, so riskParameter.staleAfter should be sufficiently long to catch some volatility (depending on volatility and leverage, a few minutes to a few hours are required)
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial/contracts/Market.sol#L485-L486
2. The leverage should be sufficiently high to catch profitable price swings (leverage = 50-100 is quite enough for this and many markets can use such leverage)
3. The market should be relatively quiet (no trades and thus oracle requests and commits happening in the time interval)

## Impact

Each round of commit function abuse allows to steal a certain (high) percentage of the amount involved. With high enough amounts, this can lead to significant loss of funds (up to all funds market has) for all market participants.

## Code Snippet

PythOracle `commit()` function has only 2 checks. No oracle requests pending:
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-oracle/contracts/pyth/PythOracle.sol#L167-L170
And commited oracle version to be later than previous commit:
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-oracle/contracts/pyth/PythOracle.sol#L175

Additionally, when getting and validating pyth price from data, it should be between MIN and MAX valid time after the specified oracleVersion, but it's easy to overcome by choosing appropriate oracleVersion needed (slightly in the past from the price itself).
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-oracle/contracts/pyth/PythOracle.sol#L190-L195

Market **does NOT** request oracle version if there is no change to position (only collateral change):
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial/contracts/Market.sol#L284

## Tool used

Manual Review

## Recommendation

User should not be able to commit price for arbitrary timestamp in the past, he must be restricted to a more recent price only. For example, consider restricting `commit()`'s oracleVersion to be at max `GRACE_PERIOD` from current `block.timestamp`.

**Comment by panprog** [comment]
Escalate

`staleAfter` parameter has different use case: it simply prevents doing anything with your account if the last oracle price is too old. You simply can't make it too short: all trading will just halt if there are no recent oracle commits, so too small `staleAfter` value will force many unrequested commits to keep protocol functioning. For example:
- granularity = 100
- staleAfter = 200
t=99: UserA requests open position [timestamp=100]
t=120: Oracle commited for timestamp=100
... (no actions for 200 seconds)
t=320: UserA requests close position -> reverts (currentTimestamp = 400, latestVersion.timestamp = 100, 400-100 > 200)
So in order for UserA to be able to execute the request, unrequested oracle commit must be made to make it fresh.

However, even 200 seconds can be just enough for the scenario described in this report: the price might quickly drop by 2% then grow by 4% during 200 seconds - and the user will be able to profit from this by commiting the price from 200 seconds ago, using this price to withdraw and then liquidate its own position for additional profit.

Realistically, `staleAfter` should be at least some 10x of the oracle granularity so that normal trading doesn't require too many unrequested commits. And this 10x amount is too large time window: user can commit any price from this price interval to catch volatility and profit off it. He should be limited to a more recent period to commit and this period should most often be much smaller than good `staleAfter` amount (which serves the other purpose). So I argue that `staleAfter` can not be used to prevent the issue described in this report and thus it should be valid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> `staleAfter` parameter has different use case: it simply prevents doing anything with your account if the last oracle price is too old. You simply can't make it too short: all trading will just halt if there are no recent oracle commits, so too small `staleAfter` value will force many unrequested commits to keep protocol functioning. For example:
> - granularity = 100
> - staleAfter = 200
> t=99: UserA requests open position [timestamp=100]
> t=120: Oracle commited for timestamp=100
> ... (no actions for 200 seconds)
> t=320: UserA requests close position -> reverts (currentTimestamp = 400, latestVersion.timestamp = 100, 400-100 > 200)
> So in order for UserA to be able to execute the request, unrequested oracle commit must be made to make it fresh.
> 
> However, even 200 seconds can be just enough for the scenario described in this report: the price might quickly drop by 2% then grow by 4% during 200 seconds - and the user will be able to profit from this by commiting the price from 200 seconds ago, using this price to withdraw and then liquidate its own position for additional profit.
> 
> Realistically, `staleAfter` should be at least some 10x of the oracle granularity so that normal trading doesn't require too many unrequested commits. And this 10x amount is too large time window: user can commit any price from this price interval to catch volatility and profit off it. He should be limited to a more recent period to commit and this period should most often be much smaller than good `staleAfter` amount (which serves the other purpose). So I argue that `staleAfter` can not be used to prevent the issue described in this report and thus it should be valid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Emedudu** [comment]
Escalate

This is invalid.

>PythOracle allows any user to commit non-requested oracle version for any timestamp after the previous commit even if it's long ago which can be abused to steal from the protocol via price manipulation and collateral removal

Keepers can only commit oracle versions that are more recent than the last recorded oracle version as guaranteed by this [check](https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-oracle/contracts/pyth/PythOracle.sol#L175).
Any price committed after the previous commit is the most recent price, so no matter how "long ago" it is, it is still more recent than the last committed price, and this is what the protocol wants - to use most recent prices

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is invalid.
> 
> >PythOracle allows any user to commit non-requested oracle version for any timestamp after the previous commit even if it's long ago which can be abused to steal from the protocol via price manipulation and collateral removal
> 
> Keepers can only commit oracle versions that are more recent than the last recorded oracle version as guaranteed by this [check](https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-oracle/contracts/pyth/PythOracle.sol#L175).
> Any price committed after the previous commit is the most recent price, so no matter how "long ago" it is, it is still more recent than the last committed price, and this is what the protocol wants - to use most recent prices
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
> Any price committed after the previous commit is the most recent price, so no matter how "long ago" it is, it is still more recent than the last committed price, and this is what the protocol wants - to use most recent prices

Yes, I agree that it's what protocol wants - a more recent price. However, the user has a choice of selecting the exact time that is good to him inside a very large time window, which can be abused by the user to his advantage at the expense of the other users.

**Comment by arjun-io** [comment]
> Realistically, staleAfter should be at least some 10x of the oracle granularity so that normal trading doesn't require too many unrequested commits.

I think this is an incorrect assumption. The `staleAfter` parameter is set to specifically counter this volatility issue, not to give better trader to UX. If many unrequested commits are required to trade, that is acceptable.

**Comment by hrishibhat** [comment]
@panprog

**Comment by panprog** [comment]
> I think this is an incorrect assumption. The `staleAfter` parameter is set to specifically counter this volatility issue, not to give better trader to UX. If many unrequested commits are required to trade, that is acceptable.

I think you underestimate what the volatility can cause. Here are some facts to consider:
- Maintenance % is set once and is extremely hard to change (increase, specifically), because it can cause mass liquidations of unsuspected users (even if notified beforehand)
- Volatility is variable and what the average and max price deviation is now, can be very different from what it will be in the future.
- During high volatility, the price often "jumps" by a large percentage in a very short time frame, so no time limit can actually stop this

Now I want to note the difference between this issue and #47 (which is similar). #47 allows to withdraw on previous price, so it basically concerns difference between high/low and open prices of the interval (profitable if high/low and open price deviates by more than maintenance margin). It was also present in Perennial V1 too.

This issue is introduced in V2 due to more flexible and permissionless oracle commit times and is more severe as it allows to use the same price deivation (high/low vs open) in the interval + liquidation fee, so it's profitable if abs((high or low)-open) + liquidation fee > maintenance. Or in the other words (since liquidation fee is % off maintenance) - it's profitable when price deviates by more than maintenance * (1 - liquidationFee).

Now, here are some actual historical data from ETH/USDT to validate my points. I use Binance historical price data as it's easily available and quite representative of the actual oracle data, even though still different ofcourse, but still should be enough to get the approximate numbers. Data can be downloaded [here](https://data.binance.vision/?prefix=data/spot/daily/klines/ETHUSDT/1m/)

Time interval: 1 minute

Period: May 2021
Max Open/Low deviation: 9.9% (2414.57 -> 2181.7)
```
1621430460000,2414.57000000,2450.00000000,2181.70000000,2199.10000000,11906.36760000,1621430519999,27576624.25260090,12878,5453.23187000,12721379.65543780,0
```

Period: June 2022
Max Open/Low deviation: 4.2% (1114.24 -> 1067.7)
```
1655316000000,1114.24000000,1135.00000000,1067.70000000,1110.32000000,14502.37520000,1655316059999,15987751.47779200,17628,7287.07670000,8034445.81456500,0
```

Period: July 2023
Max Open/Low deviation: 1.5% (1114.24 -> 1067.7)

With #47 this means that maintenance margin of 10% (leverage = 10) is enough to prevent any profitable exploits. Although with current low volatility environment this is overkill. But, for example, maintenance margin of 4% (leverage = 25, current setup in arbitrum ETH USD perennial v1 market) is not enough to prevent profitable exploit. So if the market owner sets up leverage based on current volatility environment, if volatility rises significantly in the future, `staleAfter` won't make it possible to fix this problem, and changing max leverage might not be possible. On the other hand, if owner sets very low leverage, most of the time this prevents more effective funds usage while volatility is low.

Now, with this issue, the possibility to exploit depends on liquidation fee (which is % from maintenance margin). For example, if liquidation fee = 100% of maintenance margin, this exploit will be profitable very frequently (almost always - a price difference of more than position + keeper fee is enough to make it profitable). If liquidation fee = 50%, then the volatility level of May 2021 will make any leverage < 5x vulnerable to this exploit. 

In both cases `staleAfter` doesn't really impact any of these issues. The data is for 1-minute intervals and it's not much better even for shorter intervals, even to 5-second time intervals, due to the "jumps" in price during high volatility. After checking the actual historical stats myself, I have to say that my proposed solution to this issue is actually ineffective - time limit can not stops this issue from happening. I'm not sure of the best solution to this issue right now, but most probably proposed solution to #47 (delayed withdrawals) should solve this one as well, so #47 and this one can probably be duplicates (but this one is more severe).

**Summary**
- 47 basically prevents the usage of any high enough leverage, because variable volatility and fixed maintenance margin, as well as the "jumps" in price during high volatility, makes it possible to exploit the "stale" price by withdrawing collateral, so only very high maintenance margin (very low leverage) can prevent that. Example from historical data shows that ETH/USDT price can move up to 10% within 1 minute, making the leverage of 10 or less the limit for it.
- This issue is basically 47 but with liquidation fee added to profit. So depending on liquidation fee, this can be critical (if liquidation fee is 100%, exploit is profitable very frequently) or the same as 47 (if liquidation fee is 10% or less).
- Both these issues can not be prevented by time limit such as `staleAfter` parameter.
- High maintenance margin (10%+) + low liquidation fee (<10%) will prevent both these issues from happening, but will severely limit the market owner choice of settings. 
- **It is not mentioned anywhere that liquidation fee should be low. So if any market uses liquidation fee close to 100% (regardless of maintenance margin), it will make this exploit very frequently possible with the attacker stealing a lot of funds.**

So from all points, I guess the last one should make this at least a valid medium, because when liquidation fee is set close to 100% (regardless of all the other settings), theft of funds is easily possible. And this is a possible scenario. I don't think the argument "can be mitigated by not setting liquidation fee high" is applicable, because this is possible value and it is never mentioned or limited in the code (so I believe this falls under "unexpected consequences of normal admin action")

If setting high maintenance margin and low liquidation fee is expected behavior then this and 47 are invalid, but at least developers are aware of the problems of these settings.

**Comment by panprog** [comment]
Just want to add one more thing: if minLiquidationFee is set close to minMaintenance, this is the same effect as liquidationFee close to 100%, just the absolute amount of possible theft is limited by minLiquidationFee in this case.

So, if either liquidationFee is close to 100%, or minLiquidationFee is close to minMaintenance, the issue described here is very frequent and causes loss of funds.

**Comment by arjun-io** [comment]
Thanks for the thorough explanation @panprog - really appreciate diving deep. We believe we have the correct parameters available here to minimize the effect of this volatility attack so we'll defer to the contest judges/admins for final judgment here.

**Comment by 141345** [comment]
Suggestion:
Low severity.

### jump price
My understanding, jump price is the key for the potential loss. The question is, will there be such price jump for decentralized price feed? 

In exchanges, there is difference for index/mark/last price, the index price is the average of several exchanges, also probably something like TWAP. [Binance](https://www.binance.com/en/support/faq/what-are-mark-price-and-price-index-in-usd%E2%93%A2-margined-futures-360033525071)
> the Price Index for USDⓈ-M Futures contracts derives prices from KuCoin, Huobi, OKX, HitBTC, Gate.io, Ascendex, MXC, Bitfinex, Coinbase, Bitstamp, Kraken, and Bybit.
> Mark price = Median (Price 1, Price 2, Contract Price)

The jump is most for spot trade price (the above example), because of not enough orderbook depth. As a result, there are needs for more smooth and stable index/mark price.

But for price feed, usually the provided price is index/mark, not the spot trade price.

So I believe if `staleAfter` is set properly, it can effectively protect sudden price change.

### parameter
Another aspect, the combination of high leverage and high deviation is not proper, which should not be setup in the first place.

### liquidation
Liquidation is separate issue, not the focus on this one.

**Comment by panprog** [comment]
> My understanding, jump price is the key for the potential loss. The question is, will there be such price jump for decentralized price feed?

It's not jump in price as in: a random price flunctuation up and down. What I talk about is if the price starts to quickly move directionally into either direction, then regardless of how you smooth the price between exchanges and in time (time-averaging is possible in only very limited time, like a few seconds average, otherwise the price lags too much which can be easily abused), the last commited price becomes stale rather quick. For example, in June 2022 data, 10 straight minutes:
```
1655316000000,1114.24000000,1135.00000000,1067.70000000,1110.32000000
1655316060000,1111.18000000,1129.44000000,1089.78000000,1105.33000000
1655316120000,1105.33000000,1114.75000000,1098.98000000,1100.35000000
1655316180000,1100.35000000,1102.30000000,1083.59000000,1087.92000000
1655316240000,1087.92000000,1091.80000000,1071.22000000,1078.84000000
1655316300000,1078.85000000,1089.07000000,1072.64000000,1073.76000000
1655316360000,1073.76000000,1079.30000000,1060.00000000,1061.34000000
1655316420000,1060.73000000,1069.27000000,1051.33000000,1060.61000000
1655316480000,1061.53000000,1062.62000000,1052.60000000,1054.07000000
1655316540000,1054.07000000,1066.76000000,1051.04000000,1062.38000000
```
So you can see that price quickly moves from 1114 to 1054 in 10 minutes (5.7% drop). If you're given a window of, say, 60 seconds, then you'll always find 1%+ (probably even 2%+) price difference inside this window during this drop, regardless of how it's averaged between exchanges and in time. Even if the time window is just 5-10 seconds (like 1 block), it's still possible to catch a price difference of 1%+, but `staleTime` can not be 1 block from the protocol design, so any realistic setting will not prevent such situations. This is just an example of price move in June 2022, in the other time frames exactly the same happened with higher magnitude and it can easily happen in the future as well. The point is - volatility is variable and you can't prevent this with fixed `minMaintenance` and `staleAfter` settings.

And even 1 such situation is enough to cause a lot of damage as this is a riskless profit which can be done with max available position size, so even 0.5% of profit if position allowed is $100M will cause $500K damage to the protocol

**Comment by 141345** [comment]
@arjun-io Could you please share some opinions on the above comments?

**Comment by arjun-io** [comment]
We don't have any updates on our thoughts here. We acknowledge and hear Panprog's description and believe that with normal market usage and parameter setting this type of profit taking can be minimized to 0

**Comment by panprog** [comment]
I maintain my view that this should be a valid medium.
Perennial protocol is expected to only do actions depending on price in the **next** oracle update. But collateral withdrawal still depends on price, but uses **previous** oracle update to validate availability to withdraw. Yes, it does have settings to partially mitigate this, but it breaks the whole logic of updating using future oracle prices, not previous stale ones, and this also causes severe limitation on the market settings.

This issue can be fully mitigated (for ETH market) by using max leverage of 10 or less **and** liquidationFee of less than 10% **and** minLiquidationFee less than 10% of minMaintenance. So in this sense admin can prevent it via settings, so from this point of view this can be considered low.

But:
- minLiquidationFee can be equal to minMaintenance. There is no verification nor any information on limitations about liquidationFee and minLiquidationFee.
- protocol can easily allow some 50x or even 100x leverage for ETH price if it doesn't allow withdrawal on previous price, it is restricted to 10x only because of this issue.

So my final view: yes, this can be mitigated by admin market settings, but settings themselves are severely limited by this issue. In particular, the current settings of live perennial v1 arbitrum ETH market allow 25x leverage, which is vulnerable to this issue (although it's different in v1, but similar and still possible). This indicates that admins might easily be not aware of this issue.

**Comment by hrishibhat** [comment]
Result:
Low 
Unique
After further considering all the above comments and discussions, with the correct market settings by the admin this issue can be mitigated, hence considering this a valid low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Emedudu](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/43/#issuecomment-1694980702): accepted
- [panprog](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/43/#issuecomment-1694055822): rejected
