### ISSUE TITLE
panprog - Collateral removal user action doesn't require oracle price and doesn't trigger oracle request to commit new oracle version, which can be used to front-run price updates to gain unfair advantage and profit at the expense of the other protocol users

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-perennial-judging#47]
panprog

high

# Collateral removal user action doesn't require oracle price and doesn't trigger oracle request to commit new oracle version, which can be used to front-run price updates to gain unfair advantage and profit at the expense of the other protocol users
## Summary

All user actions trigger oracle version request and can only proceed when settled with the correct oracle price. However, there is an exception: if the action only changes collateral, it is allowed to just proceed using the most recent commited oracle price available. This is a high security risk, because collateral removal can be used as "closing position" with a fee = maintaince margin. This allows to basically front-run large oracle updates, closing positions at lagging old prices. For example:
1. Alice opens 1 ETH Long position at price = $1000
2. At some later time the last commited price is $1100
3. Current price instantly drops to $1080, however it is not yet commited, so the last commited price is still $1100.
4. Instead of closing position (which will happen later at the current price of $1080 or worse), Alice can just remove max collateral available at the last commited price ($1100), keeping only the minimum required. If leverage = 100, Alice can keep $11 as collateral and withdraw $89 of profit, abandoning her position. This is equal to closing position with a fee = 1% of position notional (at the price of $1089, which is much better than the current market price).
5. Additionally, Alice can also immediately liquidate her own account (as it will be in a bad debt once the current price is commited) to get additional liquidation fees.

## Vulnerability Detail

All `Market.update()` calls request a new oracle version and add the changes to a pending position, **except** collateral update:
```solidity
        // request version
        if (!newOrder.isEmpty()) oracle.request(account);
```
Order is empty when maker, long and short are all zero (and since order is a change in user position, it's empty when position is left untouched).

Collateral is also deposited/sent to caller immediately:
```solidity
    function _update(
...
        // fund
        if (collateral.sign() == 1) token.pull(msg.sender, UFixed18Lib.from(collateral.abs()));
        if (collateral.sign() == -1) token.push(msg.sender, UFixed18Lib.from(collateral.abs()));
```

As shown in the scenario above, collateral removal can be used as a form of closing position by abandoning it, effectively bypassing the normal logic flow for all position changes, even if the bypassing "fee" is rather high (maintaince margin).

## Impact

Any user can front-run large oracle updates to gain unfair profit, put his account into a bad debt and liquidate his own account for additional profit - all at the expense of the other protocol users, effectively stealing from the protocol.

The only condition of this to happen is for the last commited price to lag the current price by maintaince margin or more. If maintaince margin is 1% (leverage = 100), this means just 1% of price lag is enough, which is easily possible.

## Code Snippet

https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial/contracts/Market.sol#L284

https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial/contracts/Market.sol#L295

## Tool used

Manual Review

## Recommendation

While immediate collateral deposit doesn't possess any risk and can be allowed, immediate collateral removal creates a high security risk, and while it's convenient for the user, for the sake of security it should also go through the pending state and be confirmed with a fresh oracle version before being sent to user as all the other position updates.

**Comment by panprog** [comment]
Escalate

This should be a valid high. The issue described here allows to abuse the delay of on-chain oracle updates during large price movements: when a large price move happens, user can remove collateral based on the last commited oracle price, which is already outdated. If the price move is larger than maintenance margin, this action will be profitable to the user (and create bad debt, which is a loss of funds for the other users). Since the user can open huge positions and/or do this regularly, this will significantly damage the protocol and its users.

Basically, perennial is supposed to allow trading only using future oracle prices. However, collateral removal == close position with fee = maintenance margin, so basically it's possible to close positions using **previous** oracle prices instead of the future oracle prices, even though with a higher fee. However, large price moves do happen, so even high fee can't stop the user from abusing this ability to front-run oracle price updates / "trade" using outdated oracle price.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should be a valid high. The issue described here allows to abuse the delay of on-chain oracle updates during large price movements: when a large price move happens, user can remove collateral based on the last commited oracle price, which is already outdated. If the price move is larger than maintenance margin, this action will be profitable to the user (and create bad debt, which is a loss of funds for the other users). Since the user can open huge positions and/or do this regularly, this will significantly damage the protocol and its users.
> 
> Basically, perennial is supposed to allow trading only using future oracle prices. However, collateral removal == close position with fee = maintenance margin, so basically it's possible to close positions using **previous** oracle prices instead of the future oracle prices, even though with a higher fee. However, large price moves do happen, so even high fee can't stop the user from abusing this ability to front-run oracle price updates / "trade" using outdated oracle price.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Emedudu** [comment]
Escalate

This is the reason for maintenance margin.

Basically, for this to be possible, the percent change in ETH price being recorded by keeper must be greater than the maintenance set by the admin.

So this will only be possible if admin sets the maintenance to be very low.

It is worth noting that current deployment and PerennialV1 audit also have this feature (that is, immediate collateral removal)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is the reason for maintenance margin.
> 
> Basically, for this to be possible, the percent change in ETH price being recorded by keeper must be greater than the maintenance set by the admin.
> 
> So this will only be possible if admin sets the maintenance to be very low.
> 
> It is worth noting that current deployment and PerennialV1 audit also have this feature (that is, immediate collateral removal) 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
> Basically, for this to be possible, the percent change in ETH price being recorded by keeper must be greater than the maintenance set by the admin.

Yes, exactly. The problem is that volatility does change, and during very volatile periods any maintenance set by admin is not enough (except extremely high values):
- During extreme volatility network is very often congested and gas prices spike, meaning keepers are unable to commit prices for a long time.
- During extreme volatility the liquidity across all exchanges shrinks and price can change quickly back and forth. Pyth Oracle has [confidence interval](https://docs.pyth.network/documentation/pythnet-price-feeds/best-practices#confidence-intervals) for this which are not used in Perennial, but they explain pretty well why these intervals are needed: 
> *At every point in time, Pyth publishes both a price and a confidence interval for each product. For example, Pyth may publish the current price of bitcoin as $50000 ± $10. Pyth publishes a confidence interval because, in real markets, there is no one single price for a product. For example, at any given time, bitcoin trades at different prices at different venues around the world. While these prices are typically similar, they can diverge for a number of reasons, such as when a cryptocurrency exchange blocks withdrawals on an asset. If this happens, prices diverge because arbitrageurs can no longer bring prices across exchanges into line. Alternatively, prices on different venues can differ simply because an asset is highly volatile at a particular point in time. At such times, bid/ask spreads tend to be wider, and trades on different markets at around the same time tend to occur at a wider range of prices.*

Due to these considerations, I believe the required maintenance is not enough to prevent collateral withdrawal at last commited price. The user can not abuse this volatility when opening/closing positions, because they happen at future unknown price, so even if very volatile, it's still fair and expected return long term should be 0.

But being able to use the latest commited price to immediately withdraw collateral when it's beneficial to user can be abused regardless of how high the maintenance margin is set: volatility which exceeds maintenance requirement can still happen. To make this more fair, the collateral withdrawal should also settle the same as positions - in this case it will be impossible to abuse this action regardless of volatility and maintenance margin.

> It is worth noting that current deployment and PerennialV1 audit also have this feature (that is, immediate collateral removal)

Yes, Perennial v1 is also vulnerable to the same problem.

**Comment by arjun-io** [comment]
The `staleAfter` param will prevent users from effectively using and old price for the maintenance calculation during withdrawal. As long as the price doesn't change by greater than the maintenance amount during the staleAfter period, a user can't profitably close their position.

**Comment by panprog** [comment]
See [comment](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/43#issuecomment-1697045812) in #43

**Comment by 141345** [comment]
Suggestion:
low severity.

Price update is gradual. "Jump" is not proper price feed. Max leverage has expected volatility, but this is not a way for profit. See comment in [jump price](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/43#issuecomment-1707959326).

**Comment by panprog** [comment]
I believe this can be resolved as a dup of #43, which is similar to this one with the same root but more severe

**Comment by hrishibhat** [comment]
Result:
Low
Unique
After further considering all the above comments and discussions, with the correct market settings by the admin this issue can be mitigated, hence considering this a valid low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Emedudu](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/47/#issuecomment-1695022274): accepted
- [panprog](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/47/#issuecomment-1693990439): rejected
