### ISSUE TITLE
panprog - No slippage protection when opening or closing positions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-perennial-judging#48]
panprog

high

# No slippage protection when opening or closing positions
## Summary

User can request to open or close position, however the request is only executed later with the price which is unknown at the request time. In case there is a large price swing between the request and fulfillment time, the user request will execute no matter what, there is no option for the user to specify the min (max) price he is willing to accept.

## Vulnerability Detail

Consider the following scenario:
1. Current ETH price = $1000. User requests to open 1 ETH long position with a view to have it opened at the price close to $1000.
2. There is a suddent spike of price to $1050 and then back to $1000. The user is unfortunate for the keeper to commit the price of $1050 to fulfill the user's request.
3. User will have 1 ETH long position opened at the price of $1050 while he expected the price to be close to $1000.
4. User is now in a loss of $50 at the current price of $1000.

There is no way for the user to prevent this scenario even if he's aware it's possible and wants to limit the execution price.

## Impact

User can not protect his requests from being executed at unwanted price levels, thus potentially losing funds.

## Code Snippet

`Market.update()` function only allows to specify new position sizes, delta collateral and protection status. No way to specify price limits to fail or execute the order:
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial/contracts/Market.sol#L76-L83

## Tool used

Manual Review

## Recommendation

Add min and max price levels user is willing to accept his request. If the price at the order settlement time is outside the price level user is willing to accept, invalidate the order.

**Comment by panprog** [comment]
Escalate

This should be a valid issue. Once the user requested a position open, he still doesn't know the execution price, but he has absolutely no control over the range he's willing to accept. And different things can happen, such as quick price spikes, network congestions with long inability for the keepers to commit prices or outright some price manipulation. Even if the user knows the price he's willing to open/close position, he can not do anything about it - once request is submitted, it will execute no matter what with no user control over it.

Most protocols allow users to set price limits. And while it's not as severe here as in, say, Uniswap, due to oracle usage, it's nonetheless important for the user to be able to control the execution price range and currently perennial doesn't provide such functionality. I understand that this might be somewhat hard to implement, but it doesn't make this a non-issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should be a valid issue. Once the user requested a position open, he still doesn't know the execution price, but he has absolutely no control over the range he's willing to accept. And different things can happen, such as quick price spikes, network congestions with long inability for the keepers to commit prices or outright some price manipulation. Even if the user knows the price he's willing to open/close position, he can not do anything about it - once request is submitted, it will execute no matter what with no user control over it.
> 
> Most protocols allow users to set price limits. And while it's not as severe here as in, say, Uniswap, due to oracle usage, it's nonetheless important for the user to be able to control the execution price range and currently perennial doesn't provide such functionality. I understand that this might be somewhat hard to implement, but it doesn't make this a non-issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 141345** [comment]
Low likelihood for the situation in PoC, that sudden price change just at the moment of open/close. And when it really happens, the loss is limited.

The slippage could be future design consideration.

Low/Info severity is more appropriate.

**Comment by panprog** [comment]
I argue that during high volatility the sudden price change back and forth is frequent and such situation is quite likely and the loss can be considerable (several percentages from the notional - with higher leverage this can be tenth of percents of the user collateral).

**Comment by 141345** [comment]
> I argue that during high volatility the sudden price change back and forth is frequent and such situation is quite likely and the loss can be considerable (several percentages from the notional - with higher leverage this can be tenth of percents of the user collateral).

Yes, during high volatility, price could change back and forth. But the loss here is when the sudden change happend just before open/close position. It requires a jump for price feed, whether the jump is plausible is in question. Because most price feed are not spot trade record, but some aggregated value from multiple sources, refer to [Binance Index Price](https://www.binance.com/en/support/faq/what-are-mark-price-and-price-index-in-usd%E2%93%A2-margined-futures-360033525071).

Another aspect, when trading, there are two types of order, market and limit. Here without slippage is market order. Whether to add the "limit" like order is protocol's design improvement.

**Comment by panprog** [comment]
> Yes, during high volatility, price could change back and forth. But the loss here is when the sudden change happend just before open/close position. It requires a jump for price feed, whether the jump is plausible is in question. Because most price feed are not spot trade record, but some aggregated value from multiple sources, refer to [Binance Index Price](https://www.binance.com/en/support/faq/what-are-mark-price-and-price-index-in-usd%E2%93%A2-margined-futures-360033525071).

During high volatility the network is very often congested and transactions are delayed by 30+ minutes due to high gas prices. Transaction execution prices spike to absurd numbers and as such oracle commits are delayed until the prices are more or less acceptable. In such periods - some transactions might go through (just before the volatility, or even randomly during the volatility), but the others - only after a long time. So besides the price feed jump, perhaps the worse problem is transaction execution times.

In the normal situation, this protection is rarely needed as price doesn't change so quick. But during high volatility, this is a very important feature to protect users from factors they can't control. In the other protocols, I've seen transactions execute *hours* after the volatility started, causing very frustrated users with very unexpected trading prices.

> Another aspect, when trading, there are two types of order, market and limit. Here without slippage is market order. Whether to add the "limit" like order is protocol's design improvement.

It's not really a limit order, just a protection against bad price: so it's more like fill-or-kill. Limit order is expected to sit in the orderbook waiting for the price the order wants before executing. Fill-or-kill is either executed in full at the price better than requested, or canceled if the price is worse than specified.

**Comment by 141345** [comment]
Yes, not quite the same. My point is, with or without slippage is more like the difference between different types of order.

The reason for slippage protection in AMM is to prevent frontrun and sandwich.
Here in perpertual exchange here, position settlement is delayed, frontrun and sandwich is not a big problem. It is only needed during high volatility. And the loss amount is also limited.

As such, the slippage protection is more like a design improvemnt rather than a vulnerability.

**Comment by 141345** [comment]
Suggestion:
Low severity is suitable.

Slippage protection in this context is more like a feature, rather than bug.
Further, the new design could introduce other issue.

**Comment by panprog** [comment]
According to sherlock rules:
> List of Issue categories that are considered valid:
> * Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high

Agree that in the context of this protocol operation, this is more like a useful feature for users to avoid loss of funds in certain market condition than an actual issue. I'd say it's borderline, because there is loss of funds involved and user can expect to be protected from price movement, and sherlock also lists slippage protection as a valid issue, that's why I reported it.

If a feature which allows user to avoid loss of funds in certain market situations is not considered valid medium, I agree this should be low/informational.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
After further discussion agree with the comment [here](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/48#issuecomment-1707945162)
Considering this a valid low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/48/#issuecomment-1694002558): rejected
